### ISSUE TITLE
Support multi value cookies?

### ISSUE THREAD

**Issue by JRaspass** [gonzus/http-xscookies#3]
CGI, Dancer, Plack, and I'm sure many other languages and libraries have the concept of a multi value cookie where the individual values are escaped and then concatenated with ampersand to form the raw header. For more details see the corresponding Dancer bug - https://github.com/PerlDancer/Dancer2/pull/1325

Would you be opposed to someone extending bake_cookie at least to take an array ref for the value? Changing crush_cookie might hurt expectations, but extending bake_cookie would be using what is currently an error.

**Comment by gonzus** [comment]
Hey, sorry for the long time to respond, had to deal with some family issues.

I am not opposed at all. Not sure how useful it would be to just modify bake_cookie without also modifying crush_cookie.

Can you provide some code? At least some tests (which would break today) showing how you expect this to work, for both bake_cookie and crush_cookie?

Cheers!

**Comment by JRaspass** [comment]
Hey, I haven't had a chance to work on the implementation yet, but I was thinking of a design something like this:

```
bake_cookie foo => [ 'bar&baz', 'qux' ];

# or

bake_cookie foo => { value => [ 'bar&baz', 'qux' ] };

# should produce a value of "foo=bar%26baz&qux"
```

So each of the array values are URI escaped and then concatenated with ampersand.

The crush side should work like this:

```
my $values = crush_cookie $cookie;

# $values could have array ref values like "{ foo => [ 'bar&baz', 'qux' ] }"
```

Obviously all of this would be in addition to the scalar interface, so some kind of SvTYPE(...) == PVAV if check at the top of back_cookie would dispatch to the escaping logic in a loop, or something. I doubt we need to worry about array ref overloading.

**Comment by gonzus** [comment]
Hi @JRaspass, I was wondering if this is still needed?

**Comment by JRaspass** [comment]
@gonzus it would definitely be a nice to have, ATM Dancer 2 works around it by using the pure perl implementation with multi value cookies.

**Comment by gonzus** [comment]
Hi again @JRaspass,

I just wanted to let you know that I have a first implementation of multi-valued cookies. I need to clean it up a bit, I expect to do that tomorrow.

Pinging @xsawyerx as well, I know he will be happy to hear this. :-)

**Comment by gonzus** [comment]
This is pushed now, will soon release a new version.

**Comment by JRaspass** [comment]
Awesome! Thanks @gonzus

**Comment by gonzus** [comment]
Just uploaded HTTP-XSCookies-0.000017.tar.gz to CPAN.

**Comment by xsawyerx** [comment]
Great stuff! :)
