### ISSUE TITLE
Weird handling of boolean flags

### ISSUE THREAD

**Issue by ccntrq** [gonzus/http-xscookies#7]
When you try to disable boolean flags like 'http_only' using a string value you can get unexpected results.

In perl the string '0' is treated as false. The C implementation of this treats it as true and sets the flags. 

You can find the related issue and discussion in the Dancer2 project:
https://github.com/PerlDancer/Dancer2/pull/1428

I wanted to fix this myself but don't see me doing this in the near future so i thought i should at least open an issue here.
You can find my attempt (which is probably wrong) here:
https://github.com/ccntrq/http-xscookies/commit/1342e712b21fdb35eaf9bf776e9c799f946f8854

**Comment by gonzus** [comment]
Absolutely right, just pushed a fix and will cut a new release in CPAN. Thanks!

**Comment by gonzus** [comment]
Uploaded HTTP-XSCookies-0.000015.tar.gz. Cheers.

**Comment by ccntrq** [comment]
Nice! Thanks for fixing it that quick. I'm glad I didn't waste my time on this as it would have taken me hours and the solution would have never been as clean and easy as this.
